sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - qt4-dev-tools
      - libxt-dev
      - libshp-dev

cache:
  ccache: true
  directories:
    - $HOME/cmake-3.1.1-Linux-x86_64
    - $HOME/VTK-Install
    - $HOME/boost_1_56_0
    - $HOME/.conan

env:
  global:
    - VTK_DIR=$HOME/VTK-Install/lib/cmake/vtk-6.3
    - BOOST_ROOT=$HOME/boost_1_56_0
matrix:
  include:
    - compiler: gcc
      env: CASE=CLI CMAKE_ARGS="-DOGS_BUILD_GUI=OFF -DOGS_BUILD_UTILS=ON"
    - compiler: clang
      env: CASE=CLI CMAKE_ARGS="-DOGS_BUILD_GUI=OFF -DOGS_BUILD_UTILS=ON"
    - compiler: gcc
      env: CASE=GUI CMAKE_ARGS="-DOGS_BUILD_GUI=ON -DOGS_BUILD_CLI=OFF -DOGS_BUILD_TESTS=OFF"
    - compiler: clang
      env: CASE=GUI CMAKE_ARGS="-DOGS_BUILD_GUI=ON -DOGS_BUILD_CLI=OFF -DOGS_BUILD_TESTS=OFF"
    - compiler: gcc
      env: CASE=CONAN CMAKE_ARGS="-DOGS_BUILD_GUI=ON -DOGS_BUILD_UTILS=ON"
    - compiler: gcc
      env: CASE=CHECK

before_install:
  - if [ "$CASE" != "CHECK" ]; then bash scripts/travis/cmake.sh; fi
  - if [ "$CASE" != "CONAN" ] && [ "$CASE" != "CHECK" ]; then bash scripts/travis/boost.sh; fi
  - if [ "$CASE" != "CONAN" ] && [ "$CASE" != "CHECK" ]; then bash scripts/travis/vtk.sh; fi
  - if [ "$CASE" == "CONAN" ] && [ "$CASE" != "CHECK" ]; then bash scripts/travis/conan.sh; fi

before_script:
  - export PATH=$HOME/cmake-3.1.1-Linux-x86_64/bin:$PATH
  - if [ "$CC" == "gcc" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi

script:
  - if [ "$CASE" == "CHECK" ]; then git diff --check `git merge-base origin/master HEAD` HEAD; fi
  - if [ "$CASE" != "CHECK" ]; then mkdir build; fi
  - if [ "$CASE" != "CHECK" ]; then cd build; fi
  - if [ "$CASE" != "CHECK" ]; then cmake $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug ..; fi
  - if [ "$CASE" != "CHECK" ]; then make -j 2; fi
  - if [ "$CASE" == "CLI" ] && [ "$CASE" != "CHECK" ]; then make tests; fi

notifications:
  hipchat:
    rooms:
      secure: kmLyt50IGFuK96xbD+VzWRRzF6UU6SdVpsn1bolKQaTCCj1rz4H1np1iUML0jeGn86DAkkHPWmFXaS2JN0EoX8L74HavJSkUfIa49cegk0je986fxucaUV1fnhFIRh6EGkpqvqE+uXs/wKHkzrkYbpHaRvJgmxQSV9kR4yRuAmw=
